# Generated by Django 3.0.6 on 2020-05-09 16:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='When object was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='When object was last updated (any of its values)')),
                ('name', models.CharField(max_length=2048)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('version', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
