# Generated by Django 3.0.6 on 2020-06-14 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('object_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseobject',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='VerseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='When object was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='When object was last updated (any of its values)')),
                ('name', models.CharField(max_length=2048)),
                ('description', models.TextField(default='')),
                ('verse_objects', models.ManyToManyField(to='object_storage.VerseObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='When object was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='When object was last updated (any of its values)')),
                ('name', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('verse_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='object_storage.VerseObject')),
                ('verse_project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='object_storage.VerseProject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
